import {
  faCoffee,
  faUserTie,
  faUsers,
  faChartLine,
  faChartPie,
  faFileExport,
  faExclamationTriangle,
  faUser,
  faCogs,
  faUserCog,
  faEye,
  faHome,
  faEnvelope,
  faBell,
  faCamera,
  faCar,
  faCloud,
  faHeart,
  faStar,
  faThumbsUp,
  faThumbsDown,
  faLock,
  faUnlock,
  faSearch,
  faShoppingCart,
  faTrash,
  faEdit,
  faSave,
  faDownload,
  faUpload,
  faPrint,
  faCalendar,
  faClock,
  faMap,
  faPhone,
  faGlobe,
  faMusic,
  faFilm,
  faBook,
  faLightbulb,
  faWrench,
  faHammer,
  faTools,
  faShieldAlt,
  faKey,
  faSignInAlt,
  faSignOutAlt,
  faSync,
  faRedo,
  faUndo,
  faBatteryFull,
  faBatteryHalf,
  faBatteryEmpty,
  faWifi,
  faEthernet,
  faSignal,
  faVolumeUp,
  faVolumeDown,
  faVolumeMute,
  faMicrophone,
  faMicrophoneSlash,
  faHeadphones,
  faDesktop,
  faLaptop,
  faTablet,
  faMobile,
  faServer,
  faDatabase,
  faCode,
  faBug,
  faTerminal,
  faFileCode,
  faFileAlt,
  faFolder,
  faFolderOpen,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClipboardQuestion,
  faClipboardUser,
  faFileClipboard,
  faBars,
  faChevronDown,
  faList,
  faGrip,
  faEllipsis,
  faEarth,
  faLayerGroup,
  faRocket,
  faInfoCircle,
} from '@fortawesome/free-solid-svg-icons';

export const iconMapping = {
  Layer: faLayerGroup,
  Coffee: faCoffee,
  UserTie: faUserTie,
  Client: faUsers,
  ChartColumnDecreasing: faChartLine,
  ChartPie: faChartPie,
  FileText: faFileExport,
  TriangleAlert: faExclamationTriangle,
  UserRound: faUser,
  Settings: faCogs,
  UserRoundCog: faUserCog,
  ScanEye: faEye,
  Home: faHome,
  Envelope: faEnvelope,
  Bell: faBell,
  Camera: faCamera,
  Car: faCar,
  Cloud: faCloud,
  Heart: faHeart,
  Star: faStar,
  ThumbsUp: faThumbsUp,
  ThumbsDown: faThumbsDown,
  Lock: faLock,
  Unlock: faUnlock,
  Search: faSearch,
  ShoppingCart: faShoppingCart,
  Trash: faTrash,
  Edit: faEdit,
  Save: faSave,
  Download: faDownload,
  Upload: faUpload,
  Print: faPrint,
  Calendar: faCalendar,
  Clock: faClock,
  Map: faMap,
  Phone: faPhone,
  Globe: faGlobe,
  Music: faMusic,
  Film: faFilm,
  Book: faBook,
  Lightbulb: faLightbulb,
  Wrench: faWrench,
  Hammer: faHammer,
  Tools: faTools,
  ShieldAlt: faShieldAlt,
  Key: faKey,
  SignInAlt: faSignInAlt,
  SignOutAlt: faSignOutAlt,
  Sync: faSync,
  Redo: faRedo,
  Undo: faUndo,
  Bars: faBars,
  BatteryFull: faBatteryFull,
  BatteryHalf: faBatteryHalf,
  BatteryEmpty: faBatteryEmpty,
  Wifi: faWifi,
  Ethernet: faEthernet,
  Signal: faSignal,
  VolumeUp: faVolumeUp,
  VolumeDown: faVolumeDown,
  VolumeMute: faVolumeMute,
  Microphone: faMicrophone,
  MicrophoneSlash: faMicrophoneSlash,
  Headphones: faHeadphones,
  Desktop: faDesktop,
  List: faList,
  Grip: faGrip,
  Laptop: faLaptop,
  Tablet: faTablet,
  Mobile: faMobile,
  Server: faServer,
  Database: faDatabase,
  Code: faCode,
  Bug: faBug,
  Terminal: faTerminal,
  FileCode: faFileCode,
  FileAlt: faFileAlt,
  Folder: faFolder,
  FolderOpen: faFolderOpen,
  Clipboard: faClipboard,
  ClipboardCheck: faClipboardCheck,
  ClipboardList: faClipboardList,
  ClipboardQuestion: faClipboardQuestion,
  ClipboardUser: faClipboardUser,
  ChevronDown: faChevronDown,
  Ellipsis: faEllipsis,
  InfoCircle: faInfoCircle,
  Earth: faEarth,
  Roket: faRocket,
} as const;

export type IconMapping = typeof iconMapping;
