import {
  faHome,
  faUser,
  faUsers,
  faCog,
  faProjectDiagram,
  faChartSimple,
  faBuildingColumns,
  faMagnifyingGlass,
  faPlus,
  faUserPlus,
  faUserEdit,
  faUserTimes,
  faTrash,
  faEdit,
  faEye,
  faList,
  faDownload,
  faFileAlt,
  faBuilding,
  faSearch,
  faSave,
  faClose,
  faFilter,
  faFileCsv,
  faFilePdf,
  faCheckCircle,
  faInfoCircle,
  faRefresh,
  faCoins,
  faCalendar,
  faCloudArrowDown,
  faArrowRotateLeft,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  home: faHome,
  user: faUser,
  users: faUsers,
  settings: faCog,
  proyect: faProjectDiagram,
  chart: faChartSimple,
  unidades: faBuildingColumns,
  search: faMagnifyingGlass,
  add: faPlus,
  'user-plus': faUserPlus,
  'user-edit': faUserEdit,
  'user-x': faUserTimes,
  delete: faTrash,
  edit: faEdit,
  eye: faEye,
  list: faList,
  download: faDownload,
  'file-text': faFileAlt,
  building: faBuilding,
  save: faSave,
  close: faClose,
  filter: faFilter,
  csv: faFileCsv,
  pdf: faFilePdf,
  'check-circle': faCheckCircle,
  'info-circle': faInfoCircle,
  refresh: faRefresh,
  coins: faCoins,
  calendar: faCalendar,
  upload: faCloudArrowDown,
  return: faArrowRotateLeft,
} as const;

import { z } from 'zod';

export const IconNameSchema = z.enum([
  'home',
  'user',
  'users',
  'settings',
  'proyect',
  'chart',
  'unidades',
  'search',
  'add',
  'user-plus',
  'user-edit',
  'user-x',
  'delete',
  'edit',
  'eye',
  'list',
  'download',
  'file-text',
  'building',
  'save',
  'close',
  'filter',
  'csv',
  'pdf',
  'check-circle',
  'info-circle',
  'refresh',
]);
